run_name: O2O_CUS15_GADAPG_GA03_DYN_DDE_R40_U3_NE480_EB1000_EN8_E1000
dataset_name: EVRPTW-D_Geo-AC-v1
data:
  generator_config: configs/amazon_hierarchy.yaml
  num_customers: 15
  num_charging_stations: 3
  mother_board_pool_size: 32
  mother_num_customers: 5000
  mother_num_charging_stations: 120
  region_reuse_limit: 200
  max_attempts_per_instance: 30
  territory_pool_path: null
  region_pool_path: null
  region_pool_shuffle: true
  region_pool_replacement_policy: cycle
  train_dataset_path: EVRPTW_Dataset/dataset_v1/dataset/train/Cus15
  train_sample_mode: shuffle_cycle
  async_instance_prefetch: false
  async_instance_workers: 8
  async_instance_queue_batches: 2
  async_multiprocessing_context: spawn
env:
  use_fast_env: true
  use_jit_mask: true
  normalize_reward: true
  reward_distance_scale_mode: dataset_single_customer_repair_median
  charging_mode: fixed_full
  info_level: light
model:
  embedding_dim: 256
  tanh_clipping: 15.0
  n_encode_layers: 2
  use_graph_token: true
  use_dynamic_decision_encoder: true
  dynamic_decision_heads: 4
critic:
  use_decomposed_critic: false
  advantage_mode: total
  value_coef_total: 1.0
  value_coef_boundary: 0.5
  value_coef_internal: 0.5
  consistency_coef: 0.1
  balanced_adv_weight_boundary: 0.3
  balanced_adv_weight_internal: 0.7
training:
  online_training: false
  epochs: 1000
  num_envs_per_gpu: 480
  n_traj: 50
  rollout_steps: 40
  ppo_step_chunk_size: 64
  ppo_update_epochs: 3
  num_minibatches: 32
  gamma: 0.99
  clip_coef: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  learning_rate: 0.0001
  weight_decay: 0.0
  max_grad_norm: 1.0
  checkpoint_interval: 50
  debug: true
  debug_log_every: 1
  profile_timing: false
  gradient_accumulation_steps: 1
  mixed_precision: true
pbrs:
  use_customer_pbrs: false
  use_repair_distance_pbrs: false
  use_feasible_ratio_pbrs: false
  use_terminal_heuristic: false
evaluation:
  eval_interval: 10
  eval_path: EVRPTW_Dataset/dataset_v1/dataset/val/Cus15
  eval_n_traj: 8
  eval_decode_mode: sample
  eval_max_steps: 40
  eval_limit: null
  eval_batch_size: 1000
  eval_num_batches: null
  eval_info_level: light
  eval_save_routes: false
offline:
  method: gadapg
  expert_solution_path: /data/Maojie/Github2/Cus15/train/gurobi_summary.csv
  expert_dataset_path: EVRPTW_Dataset/dataset_v1/dataset/train/Cus15
  expert_limit: null
  strict_replay: true
  bc_warmup_epochs: 10
  bc_warmup_coef: 1.0
  bc_batch_size: 512
  route_batch_size: 512
  bc_updates_per_epoch: 16
  route_updates_per_epoch: 1
  bc_coef: 0.1
  bc_decay: 0.95
  min_bc_coef: 0.0
  use_dapg_demo_gate: true
  use_dapg_memory_gate: true
  dapg_demo_gate_eta: 0.05
  dapg_demo_gate_margin: 0.0
advantage:
  use_group_advantage: true
  group_adv_coef: 0.3
  group_adv_clip: 3.0
  group_adv_std_floor: 5.0
  group_infeasible_penalty: 10.0
  renormalize_after_aux_advantage: true
  use_reference_advantage: false
  use_frro: false
