run_name: O2O_CUS50_AWBC_SEED3009
dataset_name: EVRPTW-D_Geo-AC-v1
data:
  num_customers: 50
  num_charging_stations: 10
  mother_board_pool_size: 8
  mother_num_customers: 5000
  mother_num_charging_stations: 120
  region_reuse_limit: 200
  max_attempts_per_instance: 30
  train_dataset_path: /data/Maojie/dataset_v1/dataset/train/Cus50
  train_sample_mode: shuffle_cycle
  async_instance_prefetch: false
env:
  use_fast_env: true
  use_jit_mask: true
  normalize_reward: true
  reward_distance_scale_mode: dataset_single_customer_repair_median
  charging_mode: fixed_full
  info_level: light
model:
  embedding_dim: 256
  tanh_clipping: 15.0
  n_encode_layers: 2
  use_graph_token: true
  use_dynamic_decision_encoder: true
  dynamic_decision_heads: 4
  dynamic_decision_delta_k: false
  dynamic_decision_delta_v: false
  dynamic_decision_delta_action_key: true
  dynamic_decision_action_bias: true
critic:
  use_decomposed_critic: false
  advantage_mode: total
training:
  online_training: false
  epochs: 2000
  num_envs_per_gpu: 256
  n_traj: 50
  rollout_steps: 90
  ppo_step_chunk_size: 16
  ppo_update_epochs: 3
  num_minibatches: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  learning_rate: 0.0001
  weight_decay: 0.0
  max_grad_norm: 1.0
  checkpoint_interval: 50
  debug: true
  debug_log_every: 1
  mixed_precision: true
pbrs:
  use_customer_pbrs: false
  use_repair_distance_pbrs: false
  use_feasible_ratio_pbrs: false
  use_terminal_heuristic: false
evaluation:
  eval_interval: 10
  eval_path: /data/Maojie/dataset_v1/dataset/val/Cus50
  eval_n_traj: 50
  eval_decode_mode: sample
  eval_max_steps: 100
  eval_batch_size: 1000
  eval_info_level: light
  eval_save_routes: false
offline:
  method: awbc
  expert_solution_path: /data/Maojie/gurobi_mul_legacy/results/train/Cus50/gurobi_summary.csv
  expert_dataset_path: /data/Maojie/dataset_v1/dataset/train/Cus50
  strict_replay: true
  bc_batch_size: 512
  bc_updates_per_epoch: 16
  bc_coef: 0.10
  awbc_coef: 0.10
  awbc_eta: 0.10
  awbc_normalize: eta_objective
  awbc_baseline: mean_successful
